### PR TITLE
Dini File For MySQL Config Informations 

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Sreyas-Sreelal** [comment]
Need to test.

**Comment by ghost** [comment]
i need a mysql database to test it

**Comment by ghost** [comment]
I'm going to take a nap (1 - 2 hours) and I'll test it then.

**Comment by ghost** [comment]
Testing this was bugging me too much, I can't sleep, lol. Anyway, the first thing that comes to mind is that you should do more fault-checking (i.e.: check if the user has actually changed the file, so it doesn't try to connect to a host called 'unknown' or a database called 'unknown').
Secondly, I'm not too fond of DINI. The filterscript already uses YSI, so why not use y_ini? The extra overhead of YSI is already there (y_ini will add approx. 1 second to the compile time [Intel i5-5200 2.2GHz]).
Thirdly, instead of prompting an error to the server console when the file doesn't exist, it's probably better to create it and put dummy-data into it.

**Comment by ghost** [comment]
I also just realised that when the gamemode is hosted on a server, the file must be put onto it too. The MySQL password is stored in plain text, which is REALLY BAD! We have to think this one through first.

**Comment by ghost** [comment]
so MySQL Password need to hashed ?

y_ini <-- this one is complied than Dini i think Dini is better

**Comment by ghost** [comment]
DINI was made in 2006 and last updated in 2008. It's outdated and VERY slow. And the extra overhead of the YSI library is already there since the filterscript already uses it, so it's better to use y_ini.

As for the password, I'm not too sure on how we'll handle this. If the user changes it manually, they are required to put a hashed version of the password there. I'll have a think about it.

**Comment by ghost** [comment]
ok

Lemme update it

**Comment by ghost** [comment]
Do u have any Database free ?

i want to test this

**Comment by ghost** [comment]
I don't have one remotely available. I use a local database to test scripts.

**Comment by Sreyas-Sreelal** [comment]
Using Dini will be a high head ache for machine as as well as the users.So merging this pointless we have to step over to Y_ini as Andy said as YSI library is being used in the script. Also the password needed to be hashed as we cant trust with hosting companies and cannot put the users in  pain.

**Pull request closed without merging**
