### PR TITLE
Little Mistake

### PR DESCRIPTION
**Pull request by ghost**
Fixing ( error 035: argument type mismatch (argument 2) )

### CODE REVIEW

**Comment by Konstantinos-Sk** [comment]
I'd rather keep the initial value for transparency (which was set to AA, not fully opaque). Modify and push the commit so I can merge it.

**Comment by ghost** [comment]
Done ?

**Comment by Konstantinos-Sk** [comment]
I meant **0xFF0000AA**, a string would still give the same error.

**Comment by ghost** [comment]
i tested it and it's work fine :=)

**Pull request closed without merging**
